spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

#logging.level.org.apache.coyote.http11: debug

file.dir: C:/Users/kcore/java/file/