spring:
  output:
    ansi:
      enabled: always
  messages:
    basename: messages, errors

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 60
  error:
    whitelabel:
      enabled: false
